name       : freerdp
version    : 2.0.0_pre1
release    : 4
source     :
    - git|https://github.com/FreeRDP/FreeRDP.git : 4d401b44c03b420b64573c0df404e6e3301d4f83
license    : Apache-2.0
component  : network.util
summary    : FreeRDP is a free remote desktop protocol client
description: |
    FreeRDP is a free remote desktop protocol client
patterns   :
    - devel: /usr/lib64/cmake
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xv)
    - cups-devel
setup      : |
    %cmake \
        -DWITH_PULSE=ON \
        -DWITH_CUPS=ON \
        -DWITH_WAYLAND=OFF \
        -DWITH_MANPAGES=OFF \
        .
build      : |
    %make
install    : |
    %make_install
