name       : freerdp
version    : 2.0.0_rc1
release    : 3
source     :
    - https://github.com/FreeRDP/FreeRDP/archive/2.0.0-rc1.tar.gz : a2c1c83072489d56da78bbe76c29729022f5c35a3ec3a1ce26cea8823de043c2
license    : Apache-2.0
component  : network.util
summary    : FreeRDP is a free remote desktop protocol client
description: |
    FreeRDP is a free remote desktop protocol client
patterns   :
    - devel: /usr/lib64/cmake
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xv)
    - cups-devel
setup      : |
    %cmake \
        -DWITH_PULSE=ON \
        -DWITH_CUPS=ON \
        -DWITH_WAYLAND=OFF \
        -DWITH_MANPAGES=OFF \
        .
build      : |
    %make
install    : |
    %make_install
