name       : freerdp
version    : 2.4.1
release    : 21
source     :
    - https://github.com/FreeRDP/FreeRDP/releases/download/2.4.1/freerdp-2.4.1.tar.gz : ef75c87926643a0d0041f6556e343ac037380d4260c64885e7cdd20da0147edf
license    : Apache-2.0
component  : network.util
summary    : FreeRDP is a free remote desktop protocol client
description: |
    FreeRDP is a free remote desktop protocol client
patterns   :
    - devel : /usr/lib64/cmake
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(libpcsclite)
    - pkgconfig(libusbredirhost)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xtst)
    - pkgconfig(xv)
    - cups-devel
setup      : |
    %cmake_ninja \
        -DWITH_SSE2=ON \
        -DWITH_SERVER=ON \
        -DWITH_SWSCALE=ON \
        -DWITH_WAYLAND=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
