name       : freerdp
version    : 2.4.0
release    : 20
source     :
    - https://github.com/FreeRDP/FreeRDP/releases/download/2.4.0/freerdp-2.4.0.tar.gz : 10ec9b06d74182b354ae288c8e621d94c0fb189b0c3b14a59867ab4c414c08b5
license    : Apache-2.0
component  : network.util
summary    : FreeRDP is a free remote desktop protocol client
description: |
    FreeRDP is a free remote desktop protocol client
patterns   :
    - devel : /usr/lib64/cmake
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(libpcsclite)
    - pkgconfig(libusbredirhost)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xtst)
    - pkgconfig(xv)
    - cups-devel
setup      : |
    %cmake_ninja \
        -DWITH_SSE2=ON \
        -DWITH_SERVER=ON \
        -DWITH_SWSCALE=ON \
        -DWITH_WAYLAND=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
