name       : freerdp
version    : 2.8.0
release    : 26
source     :
    - https://github.com/FreeRDP/FreeRDP/releases/download/2.8.0/freerdp-2.8.0.tar.gz : fd26a41c367ea1f23a06716725d19efa41fd572c4536348d39b3465b116b3703
homepage   : https://www.freerdp.com/
license    : Apache-2.0
component  : network.util
summary    : FreeRDP is a free remote desktop protocol client
description: |
    FreeRDP is a free implementation of the Remote Desktop Protocol (RDP).
patterns   :
    - devel : /usr/lib64/cmake
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(libpcsclite)
    - pkgconfig(libusbredirhost)
    - pkgconfig(wayland-client)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xtst)
    - pkgconfig(xv)
    - cups-devel
setup      : |
    %cmake_ninja \
        -DWITH_SSE2=ON \
        -DWITH_SERVER=ON \
        -DWITH_SWSCALE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
