name       : freerdp
version    : 1.2.0
release    : 1
source     :
    - https://github.com/FreeRDP/FreeRDP/archive/1.2.0-beta1+android9.tar.gz : b4e7810d90ee8a81075674c4aa9412dcd5409980a653f9059c05969927253ca0
license    : Apache-2.0
summary    : FreeRDP is a free remote desktop protocol client
description: |
    FreeRDP is a free remote desktop protocol client
patterns   :
    - devel: /usr/lib64/cmake
builddeps  :
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(x11)
    - pkgconfig(xrender)
    - pkgconfig(xfixes)
    - pkgconfig(xinerama)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - pkgconfig(xshmfence)
    - pkgconfig(xv)
    - pkgconfig(xi)
    - pkgconfig(xkbfile)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(alsa)
    - cups-devel
setup      : |
    %patch -p1 < $pkgfiles/cmake-fail.patch
    %cmake . -DWITH_PULSE=ON -DWITH_MANPAGES=OFF -DWITH_CHANNELS=ON -DSTATIC_CHANNELS=OFF -DWITH_SSE2=ON 
build      : |
    %make
install    : |
    %make_install
