name       : freerdp
version    : 2.1.2
release    : 15
source     :
    - git|https://github.com/FreeRDP/FreeRDP.git : 2.1.2
license    : Apache-2.0
component  : network.util
summary    : FreeRDP is a free remote desktop protocol client
description: |
    FreeRDP is a free remote desktop protocol client
patterns   :
    - devel : /usr/lib64/cmake
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo-egl)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(libpcsclite)
    - pkgconfig(libusbredirhost)
    - pkgconfig(x11)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xshmfence)
    - pkgconfig(xtst)
    - pkgconfig(xv)
    - cups-devel
setup      : |
    %cmake_ninja \
        -DWITH_CUPS=ON \
        -DWITH_PULSE=ON \
        -DWITH_SSE2=ON \
        -DWITH_SERVER=ON \
        -DWITH_WAYLAND=OFF \
        -DWITH_MANPAGES=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
